// Copyright (c) François Paradis
// This file is part of Mox, a card game simulator.
// 
// Mox is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, version 3 of the License.
// 
// Mox is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Mox.  If not, see <http://www.gnu.org/licenses/>.
namespace Mox
{
    /// <summary>
    /// Card sub-types.
    /// </summary>
    public enum SubType
    {
        // Basic Land
        Plains,
        Island,
        Swamp,
        Mountain,
        Forest,

        // Other Land
        Desert,
        Gate,
        Lair,
        Locus,
        Mine,
        PowerPlant,
        Tower,
        Urzas,

        // Enchantment
        Aura,
        Curse,
        Shrine,

        // Artifact
        Equipment,
        Fortification,
        Contraption,

        // Spell
        Arcane,
        Trap,

        // Creature
        Advisor,
        Ally,
        Angel,
        Anteater,
        Antelope,
        Ape,
        Archer,
        Archon,
        Artificer,
        Assassin,
        AssemblyWorker,
        Atog,
        Aurochs,
        Avatar,
        Badger,
        Barbarian,
        Basilisk,
        Bat,
        Bear,
        Beast,
        Beeble,
        Berserker,
        Bird,
        Boar,
        Bringer,
        Brushwagg,
        Camel,
        Carrier,
        Cat,
        Centaur,
        Cephalid,
        Chimera,
        Cleric,
        Cockatrice,
        Construct,
        Crab,
        Crocodile,
        Cyclops,
        Dauthi,
        Demon,
        Devil,
        Djinn,
        Dragon,
        Drake,
        Dreadnought,
        Drone,
        Druid,
        Dryad,
        Dwarf,
        Efreet,
        Egg,
        Elder,
        Eldrazi,
        Elemental,
        Elephant,
        Elf,
        Elk,
        Eye,
        Faerie,
        Ferret,
        Fish,
        Flagbearer,
        Fox,
        Frog,
        Fungus,
        Gargoyle,
        Giant,
        Gnome,
        Goat,
        Goblin,
        God,
        Golem,
        Gorgon,
        Gremlin,
        Griffin,
        Hag,
        Harpy,
        Hellion,
        Hippo,
        Hippogriff,
        Homarid,
        Homunculus,
        Horror,
        Horse,
        Hound,
        Human,
        Hydra,
        Hyena,
        Illusion,
        Imp,
        Incarnation,
        Insect,
        Jellyfish,
        Juggernaut,
        Kavu,
        Kirin,
        Kithkin,
        Knight,
        Kobold,
        Kor,
        Kraken,
        Lamia,
        Lammasu,
        Leech,
        Leviathan,
        Lhurgoyf,
        Licid,
        Lizard,
        Manticore,
        Masticore,
        Mercenary,
        Merfolk,
        Metathran,
        Minion,
        Minotaur,
        Monger,
        Mongoose,
        Monk,
        Moonfolk,
        Mutant,
        Myr,
        Mystic,
        Naga,
        Nautilus,
        Nephilim,
        Nightmare,
        Nightstalker,
        Ninja,
        Noggle,
        Nomad,
        Nymph,
        Octopus,
        Ogre,
        Ooze,
        Orc,
        Orgg,
        Ouphe,
        Ox,
        Oyster,
        Pegasus,
        Pest,
        Phelddagrif,
        Phoenix,
        Pirate,
        Plant,
        Praetor,
        Processor,
        Rabbit,
        Rat,
        Rebel,
        Rhino,
        Rigger,
        Rogue,
        Sable,
        Salamander,
        Samurai,
        Satyr,
        Scarecrow,
        Scorpion,
        Scout,
        Serpent,
        Shade,
        Shaman,
        Shapeshifter,
        Sheep,
        Siren,
        Skeleton,
        Slith,
        Sliver,
        Slug,
        Snake,
        Soldier,
        Soltari,
        Spawn,
        Specter,
        Spellshaper,
        Sphinx,
        Spider,
        Spike,
        Spirit,
        Sponge,
        Squid,
        Squirrel,
        Starfish,
        Surrakar,
        Thalakos,
        Thopter,
        Thrull,
        Treefolk,
        Troll,
        Turtle,
        Unicorn,
        Vampire,
        Vedalken,
        Viashino,
        Volver,
        Wall,
        Warrior,
        Weird,
        Werewolf,
        Whale,
        Wizard,
        Wolf,
        Wolverine,
        Wombat,
        Worm,
        Wraith,
        Wurm,
        Yeti,
        Zombie,
        Zubera,

        // Planewalkers
        Ajani, 
        Ashiok,
        Bolas, 
        Chandra, 
        Domri,
        Elspeth, 
        Garruk, 
        Gideon, 
        Jace, 
        Liliana, 
        Karn,
        Kiora,
        Koth,
        Narset,
        Nissa,
        Nixilis,
        Ral,
        Sarkhan, 
        Sorin, 
        Tamiyo,
        Tibalt,
        Tezzeret,
        Ugin,
        Venser,
        Vraska,
        Xenagos,
    }
}